apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: portfolio-transaction-processing
  namespace: lotus-core
spec:
  scaleTargetRef:
    name: portfolio-transaction-processing
  minReplicaCount: 2
  maxReplicaCount: 12
  pollingInterval: 15
  cooldownPeriod: 120
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka:9092
        consumerGroup: portfolio_transaction_processing_group
        topic: transactions.persisted
        lagThreshold: "200"
        offsetResetPolicy: earliest
    - type: kafka
      metadata:
        bootstrapServers: kafka:9092
        consumerGroup: portfolio_transaction_replay_request_group
        topic: transactions.reprocessing.requested
        lagThreshold: "200"
        offsetResetPolicy: earliest
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: valuation-calculator-scaledobject
  namespace: lotus-core
spec:
  scaleTargetRef:
    name: position-valuation-calculator
  minReplicaCount: 2
  maxReplicaCount: 10
  pollingInterval: 15
  cooldownPeriod: 120
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka:9092
        consumerGroup: position_valuation_group_jobs
        topic: valuation_required
        lagThreshold: "150"
        offsetResetPolicy: latest
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: timeseries-position-scaledobject
  namespace: lotus-core
spec:
  scaleTargetRef:
    name: timeseries-generator
  minReplicaCount: 1
  maxReplicaCount: 6
  pollingInterval: 20
  cooldownPeriod: 240
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka:9092
        consumerGroup: timeseries_generator_group_positions
        topic: daily_position_snapshot_persisted
        lagThreshold: "400"
        offsetResetPolicy: latest
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: timeseries-portfolio-scaledobject
  namespace: lotus-core
spec:
  scaleTargetRef:
    name: timeseries-generator
  minReplicaCount: 1
  maxReplicaCount: 6
  pollingInterval: 20
  cooldownPeriod: 240
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka:9092
        consumerGroup: timeseries_generator_group_portfolios
        topic: portfolio_aggregation_required
        lagThreshold: "400"
        offsetResetPolicy: latest
