from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Header, status

from src.services.query_service.app.advisory_simulation.models import (
    ProposalResult,
    ProposalSimulateRequest,
)
from src.services.query_service.app.services.advisory_simulation_service import (
    execute_advisory_simulation,
)

router = APIRouter(prefix="/integration/advisory/proposals", tags=["Integration"])


@router.post(
    "/simulate-execution",
    response_model=ProposalResult,
    status_code=status.HTTP_200_OK,
    summary="Execute Canonical Advisory Simulation",
    description=(
        "Execute a canonical advisory proposal simulation request inside lotus-core. "
        "This endpoint is intended for lotus-advise after advisory context resolution, "
        "request hashing, and lifecycle/idempotency orchestration have already occurred."
    ),
)
async def simulate_advisory_execution(
    request: ProposalSimulateRequest,
    request_hash: Annotated[
        str | None,
        Header(
            alias="X-Request-Hash",
            description=(
                "Optional canonical request hash generated by the caller for lineage parity."
            ),
        ),
    ] = None,
    idempotency_key: Annotated[
        str | None,
        Header(
            alias="Idempotency-Key",
            description="Optional caller idempotency key preserved in result lineage.",
        ),
    ] = None,
    correlation_id: Annotated[
        str | None,
        Header(
            alias="X-Correlation-Id",
            description="Optional caller correlation identifier propagated into the result.",
        ),
    ] = None,
) -> ProposalResult:
    return execute_advisory_simulation(
        request=request,
        request_hash=request_hash,
        idempotency_key=idempotency_key,
        correlation_id=correlation_id,
    )
