"""Transitional transaction type imports during shared domain package migration."""

from .domain.transaction.type_registry import (
    DEFAULT_STRATEGY,
    INCOME_RECOGNITION_TRANSACTION_TYPES,
    INTERNAL_GENERATED,
    LIMITED,
    MIGRATION_ONLY,
    PRODUCTION_BOOKING_TRANSACTION_TYPES,
    SUPPORTED,
    TARGET_NOT_IMPLEMENTED,
    TARGET_NOT_IMPLEMENTED_TRANSACTION_TYPES,
    TRANSACTION_TYPE_CODES,
    TRANSACTION_TYPE_REGISTRY,
    TransactionTypeDefinition,
    get_transaction_type_definition,
    is_production_booking_transaction_type,
    is_registered_transaction_type,
    production_transaction_types_for_lifecycle_families,
    production_transaction_types_for_position_effects,
    require_registered_transaction_type,
)

__all__ = [
    "DEFAULT_STRATEGY",
    "INCOME_RECOGNITION_TRANSACTION_TYPES",
    "INTERNAL_GENERATED",
    "LIMITED",
    "MIGRATION_ONLY",
    "PRODUCTION_BOOKING_TRANSACTION_TYPES",
    "SUPPORTED",
    "TARGET_NOT_IMPLEMENTED",
    "TARGET_NOT_IMPLEMENTED_TRANSACTION_TYPES",
    "TRANSACTION_TYPE_CODES",
    "TRANSACTION_TYPE_REGISTRY",
    "TransactionTypeDefinition",
    "get_transaction_type_definition",
    "is_production_booking_transaction_type",
    "is_registered_transaction_type",
    "production_transaction_types_for_lifecycle_families",
    "production_transaction_types_for_position_effects",
    "require_registered_transaction_type",
]
