"""Define stable reason codes for ordinary transaction booking validation."""

from enum import StrEnum


class BuyValidationReasonCode(StrEnum):
    """Identify canonical BUY validation failures."""

    INVALID_TRANSACTION_TYPE = "BUY_001_INVALID_TRANSACTION_TYPE"
    MISSING_SETTLEMENT_DATE = "BUY_002_MISSING_SETTLEMENT_DATE"
    NON_POSITIVE_QUANTITY = "BUY_003_NON_POSITIVE_QUANTITY"
    NON_POSITIVE_GROSS_AMOUNT = "BUY_004_NON_POSITIVE_GROSS_AMOUNT"
    MISSING_TRADE_CURRENCY = "BUY_005_MISSING_TRADE_CURRENCY"
    MISSING_BOOK_CURRENCY = "BUY_006_MISSING_BOOK_CURRENCY"
    INVALID_DATE_ORDER = "BUY_007_INVALID_DATE_ORDER"
    MISSING_LINKAGE_IDENTIFIER = "BUY_008_MISSING_LINKAGE_IDENTIFIER"
    MISSING_POLICY_METADATA = "BUY_009_MISSING_POLICY_METADATA"


class SellValidationReasonCode(StrEnum):
    """Identify canonical SELL validation failures."""

    INVALID_TRANSACTION_TYPE = "SELL_001_INVALID_TRANSACTION_TYPE"
    MISSING_SETTLEMENT_DATE = "SELL_002_MISSING_SETTLEMENT_DATE"
    NON_POSITIVE_QUANTITY = "SELL_003_NON_POSITIVE_QUANTITY"
    NON_POSITIVE_GROSS_AMOUNT = "SELL_004_NON_POSITIVE_GROSS_AMOUNT"
    MISSING_TRADE_CURRENCY = "SELL_005_MISSING_TRADE_CURRENCY"
    MISSING_BOOK_CURRENCY = "SELL_006_MISSING_BOOK_CURRENCY"
    INVALID_DATE_ORDER = "SELL_007_INVALID_DATE_ORDER"
    MISSING_LINKAGE_IDENTIFIER = "SELL_008_MISSING_LINKAGE_IDENTIFIER"
    MISSING_POLICY_METADATA = "SELL_009_MISSING_POLICY_METADATA"


class DividendValidationReasonCode(StrEnum):
    """Identify canonical DIVIDEND validation failures."""

    INVALID_TRANSACTION_TYPE = "DIVIDEND_001_INVALID_TRANSACTION_TYPE"
    MISSING_SETTLEMENT_DATE = "DIVIDEND_002_MISSING_SETTLEMENT_DATE"
    NON_ZERO_QUANTITY = "DIVIDEND_003_NON_ZERO_QUANTITY"
    NON_ZERO_PRICE = "DIVIDEND_004_NON_ZERO_PRICE"
    NON_POSITIVE_GROSS_AMOUNT = "DIVIDEND_005_NON_POSITIVE_GROSS_AMOUNT"
    MISSING_TRADE_CURRENCY = "DIVIDEND_006_MISSING_TRADE_CURRENCY"
    MISSING_BOOK_CURRENCY = "DIVIDEND_007_MISSING_BOOK_CURRENCY"
    INVALID_DATE_ORDER = "DIVIDEND_008_INVALID_DATE_ORDER"
    MISSING_LINKAGE_IDENTIFIER = "DIVIDEND_009_MISSING_LINKAGE_IDENTIFIER"
    MISSING_POLICY_METADATA = "DIVIDEND_010_MISSING_POLICY_METADATA"
    MISSING_EXTERNAL_CASH_LINK = "DIVIDEND_011_MISSING_EXTERNAL_CASH_LINK"
    MISSING_SETTLEMENT_CASH_ACCOUNT = "DIVIDEND_012_MISSING_SETTLEMENT_CASH_ACCOUNT"


class InterestValidationReasonCode(StrEnum):
    """Identify canonical INTEREST validation failures."""

    INVALID_TRANSACTION_TYPE = "INTEREST_001_INVALID_TRANSACTION_TYPE"
    MISSING_SETTLEMENT_DATE = "INTEREST_002_MISSING_SETTLEMENT_DATE"
    NON_ZERO_QUANTITY = "INTEREST_003_NON_ZERO_QUANTITY"
    NON_ZERO_PRICE = "INTEREST_004_NON_ZERO_PRICE"
    NON_POSITIVE_GROSS_AMOUNT = "INTEREST_005_NON_POSITIVE_GROSS_AMOUNT"
    MISSING_TRADE_CURRENCY = "INTEREST_006_MISSING_TRADE_CURRENCY"
    MISSING_BOOK_CURRENCY = "INTEREST_007_MISSING_BOOK_CURRENCY"
    INVALID_DATE_ORDER = "INTEREST_008_INVALID_DATE_ORDER"
    MISSING_LINKAGE_IDENTIFIER = "INTEREST_009_MISSING_LINKAGE_IDENTIFIER"
    MISSING_POLICY_METADATA = "INTEREST_010_MISSING_POLICY_METADATA"
    MISSING_EXTERNAL_CASH_LINK = "INTEREST_011_MISSING_EXTERNAL_CASH_LINK"
    INVALID_INTEREST_DIRECTION = "INTEREST_012_INVALID_INTEREST_DIRECTION"
    NEGATIVE_WITHHOLDING_TAX = "INTEREST_013_NEGATIVE_WITHHOLDING_TAX"
    NEGATIVE_OTHER_DEDUCTIONS = "INTEREST_014_NEGATIVE_OTHER_DEDUCTIONS"
    NET_INTEREST_RECONCILIATION_MISMATCH = "INTEREST_015_NET_RECONCILIATION_MISMATCH"
    MISSING_SETTLEMENT_CASH_ACCOUNT = "INTEREST_016_MISSING_SETTLEMENT_CASH_ACCOUNT"


TransactionValidationReasonCode = (
    BuyValidationReasonCode
    | SellValidationReasonCode
    | DividendValidationReasonCode
    | InterestValidationReasonCode
)
