from pathlib import Path

import pytest

from scripts.development import update_ci_tooling_lock as lock


def test_normalized_lock_removes_machine_paths_and_interpreter_drift(tmp_path: Path) -> None:
    root = tmp_path / "lotus-core"
    raw = (
        "# autogenerated with Python 3.13\n"
        "# command with machine path\n"
        "demo==1.2.3\n"
        f"    # via -r {root.as_posix()}/requirements/ci-tooling.in\n"
    )

    first = lock.normalize_compiled_lock(raw, platform="linux/amd64", root=root)
    second = lock.normalize_compiled_lock(raw, platform="linux/amd64", root=root)

    assert first == second
    assert str(root) not in first
    assert "Python 3.13" not in first
    assert "pip==26.1.2; pip-tools==7.5.3; Python 3.11; platform linux/amd64" in first
    assert "# via -r requirements/ci-tooling.in" in first


def test_input_requirements_reject_floating_dependency(tmp_path: Path) -> None:
    path = tmp_path / "requirements.in"
    path.write_text("stable==1.0.0\nfloating>=2\n", encoding="utf-8")

    with pytest.raises(lock.ToolingLockError, match="not an exact dependency pin"):
        lock._input_requirements(path)


def test_input_requirements_accept_pinned_extras_and_includes(tmp_path: Path) -> None:
    path = tmp_path / "requirements.in"
    path.write_text("-r other.txt\ntestcontainers[kafka]==4.14.2\n", encoding="utf-8")

    assert lock._input_requirements(path) == ["testcontainers[kafka]==4.14.2"]
