from pathlib import Path

import pytest

from scripts.development import update_ci_tooling_lock as lock


def test_normalized_lock_removes_machine_paths_and_interpreter_drift(tmp_path: Path) -> None:
    root = tmp_path / "lotus-core"
    raw = (
        "# autogenerated with Python 3.13\n"
        "# command with machine path\n"
        "demo==1.2.3\n"
        f"    # via -r {root.as_posix()}/requirements/ci-tooling.in\n"
    )

    first = lock.normalize_compiled_lock(raw, platform="linux/amd64", root=root)
    second = lock.normalize_compiled_lock(raw, platform="linux/amd64", root=root)

    assert first == second
    assert str(root) not in first
    assert "Python 3.13" not in first
    assert "pip==26.2.1; pip-tools==7.6.1; Python 3.11; platform linux/amd64" in first
    assert "# via -r requirements/ci-tooling.in" in first


def test_input_requirements_reject_floating_dependency(tmp_path: Path) -> None:
    path = tmp_path / "requirements.in"
    path.write_text("stable==1.0.0\nfloating>=2\n", encoding="utf-8")

    with pytest.raises(lock.ToolingLockError, match="not an exact dependency pin"):
        lock._input_requirements(path)


def test_input_requirements_accept_pinned_extras_and_includes(tmp_path: Path) -> None:
    path = tmp_path / "requirements.in"
    path.write_text("-r other.txt\ntestcontainers[kafka]==4.14.2\n", encoding="utf-8")

    assert lock._input_requirements(path) == ["testcontainers[kafka]==4.14.2"]


def test_platform_runtime_constraints_are_distinct() -> None:
    assert lock.WINDOWS_RUNTIME_LOCK.name == "shared-runtime-windows.lock.txt"
    assert lock.LINUX_TOOLING_LOCK.name == "ci-tooling.lock.txt"


def test_replay_seeds_existing_output_but_update_resolves_fresh(
    tmp_path: Path,
) -> None:
    committed_lock = tmp_path / "ci-tooling-windows.lock.txt"
    committed_lock.write_text("stable==1.0.0\n", encoding="utf-8")
    replay_output = tmp_path / "replay.txt"
    update_output = tmp_path / "update.txt"

    lock._seed_replay_output(replay_output, committed_lock)
    lock._seed_replay_output(update_output, None)

    assert replay_output.read_text(encoding="utf-8") == "stable==1.0.0\n"
    assert not update_output.exists()


def test_replay_fails_closed_when_committed_lock_is_missing(tmp_path: Path) -> None:
    with pytest.raises(lock.ToolingLockError, match="missing.lock is unavailable for replay"):
        lock._seed_replay_output(tmp_path / "output.txt", tmp_path / "missing.lock")


def test_linux_replay_cleans_temporary_directory_when_seed_fails(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    temp_dir = tmp_path / "linux-replay"
    temp_dir.mkdir()
    monkeypatch.setattr(lock.tempfile, "mkdtemp", lambda *, prefix: str(temp_dir))

    with pytest.raises(lock.ToolingLockError, match="missing.lock is unavailable for replay"):
        lock._compile_linux_in_exact_base(replay_lock=tmp_path / "missing.lock")

    assert not temp_dir.exists()


def test_windows_check_replays_committed_closure(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    committed_lock = tmp_path / "ci-tooling-windows.lock.txt"
    committed_lock.write_text("compiled\n", encoding="utf-8")
    observed: list[Path | None] = []

    monkeypatch.setattr(lock, "WINDOWS_TOOLING_LOCK", committed_lock)
    monkeypatch.setattr(lock, "validate_inputs", lambda: None)
    monkeypatch.setattr(lock.sys, "platform", "win32")
    monkeypatch.setattr(
        lock,
        "_compile_with_host_python",
        lambda *, replay_lock=None: observed.append(replay_lock) or "raw",
    )
    monkeypatch.setattr(
        lock,
        "normalize_compiled_lock",
        lambda _content, *, platform: "compiled\n",
    )

    lock.compile_locks_for_platform(check=True, platform="windows")

    assert observed == [committed_lock]


def test_windows_update_resolves_without_replay_seed(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    output_lock = tmp_path / "ci-tooling-windows.lock.txt"
    observed: list[Path | None] = []

    monkeypatch.setattr(lock, "WINDOWS_TOOLING_LOCK", output_lock)
    monkeypatch.setattr(lock, "validate_inputs", lambda: None)
    monkeypatch.setattr(lock.sys, "platform", "win32")
    monkeypatch.setattr(
        lock,
        "_compile_with_host_python",
        lambda *, replay_lock=None: observed.append(replay_lock) or "raw",
    )
    monkeypatch.setattr(
        lock,
        "normalize_compiled_lock",
        lambda _content, *, platform: "updated\n",
    )

    lock.compile_locks_for_platform(check=False, platform="windows")

    assert observed == [None]
    assert output_lock.read_text(encoding="utf-8") == "updated\n"
