"""Define the read-only source contract for canonical FX transaction values."""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import Protocol


class FxTransactionSource(Protocol):
    """Expose persisted FX component fields without requiring mutable records."""

    @property
    def transaction_id(self) -> str: ...

    @property
    def transaction_type(self) -> str: ...

    @property
    def component_type(self) -> str | None: ...

    @property
    def component_id(self) -> str | None: ...

    @property
    def linked_component_ids(self) -> tuple[str, ...] | list[str] | None: ...

    @property
    def portfolio_id(self) -> str: ...

    @property
    def instrument_id(self) -> str: ...

    @property
    def security_id(self) -> str: ...

    @property
    def transaction_date(self) -> datetime: ...

    @property
    def settlement_date(self) -> datetime | None: ...

    @property
    def quantity(self) -> Decimal: ...

    @property
    def price(self) -> Decimal: ...

    @property
    def gross_transaction_amount(self) -> Decimal: ...

    @property
    def trade_currency(self) -> str: ...

    @property
    def currency(self) -> str: ...

    @property
    def pair_base_currency(self) -> str | None: ...

    @property
    def pair_quote_currency(self) -> str | None: ...

    @property
    def fx_rate_quote_convention(self) -> str | None: ...

    @property
    def buy_currency(self) -> str | None: ...

    @property
    def sell_currency(self) -> str | None: ...

    @property
    def buy_amount(self) -> Decimal | None: ...

    @property
    def sell_amount(self) -> Decimal | None: ...

    @property
    def contract_rate(self) -> Decimal | None: ...

    @property
    def economic_event_id(self) -> str | None: ...

    @property
    def linked_transaction_group_id(self) -> str | None: ...

    @property
    def calculation_policy_id(self) -> str | None: ...

    @property
    def calculation_policy_version(self) -> str | None: ...

    @property
    def fx_cash_leg_role(self) -> str | None: ...

    @property
    def linked_fx_cash_leg_id(self) -> str | None: ...

    @property
    def settlement_status(self) -> str | None: ...

    @property
    def fx_contract_id(self) -> str | None: ...

    @property
    def fx_contract_open_transaction_id(self) -> str | None: ...

    @property
    def fx_contract_close_transaction_id(self) -> str | None: ...

    @property
    def settlement_of_fx_contract_id(self) -> str | None: ...

    @property
    def swap_event_id(self) -> str | None: ...

    @property
    def near_leg_group_id(self) -> str | None: ...

    @property
    def far_leg_group_id(self) -> str | None: ...

    @property
    def spot_exposure_model(self) -> str | None: ...

    @property
    def fx_realized_pnl_mode(self) -> str | None: ...

    @property
    def realized_capital_pnl_local(self) -> Decimal | None: ...

    @property
    def realized_fx_pnl_local(self) -> Decimal | None: ...

    @property
    def realized_total_pnl_local(self) -> Decimal | None: ...

    @property
    def realized_capital_pnl_base(self) -> Decimal | None: ...

    @property
    def realized_fx_pnl_base(self) -> Decimal | None: ...

    @property
    def realized_total_pnl_base(self) -> Decimal | None: ...
