"""Define stable corporate-action validation reason codes."""

from enum import StrEnum


class CorporateActionValidationReasonCode(StrEnum):
    """Classify invalid Corporate Action Bundle A booking state."""

    INVALID_TRANSACTION_TYPE = "INVALID_TRANSACTION_TYPE"
    MISSING_PARENT_EVENT_REFERENCE = "MISSING_PARENT_EVENT_REFERENCE"
    MISSING_LINKAGE_IDENTIFIER = "MISSING_LINKAGE_IDENTIFIER"
    MISSING_SOURCE_INSTRUMENT_ID = "MISSING_SOURCE_INSTRUMENT_ID"
    MISSING_TARGET_INSTRUMENT_ID = "MISSING_TARGET_INSTRUMENT_ID"
    MISSING_CASH_CONSIDERATION_LINK = "MISSING_CASH_CONSIDERATION_LINK"
    INCONSISTENT_CASH_CONSIDERATION_LINK = "INCONSISTENT_CASH_CONSIDERATION_LINK"
