"""Generate the shared runtime input set and compiled lock file."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
RUNTIME_INPUT = REPO_ROOT / "requirements" / "shared-runtime.in"
RUNTIME_LOCK = REPO_ROOT / "requirements" / "shared-runtime.lock.txt"
WINDOWS_RUNTIME_LOCK = REPO_ROOT / "requirements" / "shared-runtime-windows.lock.txt"
PIP_TOOLS_VERSION = "7.6.1"
PIP_VERSION = "26.2.1"
LINUX_COMPILE_IMAGE = (
    "python:3.11-slim-bookworm@"
    "sha256:97b0eafb29f5ebfba254be840115b2f3bc24ff6ff3de9b905e04b74ee7227ba6"
)
_PROJECT_NAME_SEPARATOR = re.compile(r"[-_.]+")
_DEPENDENCY_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*")


def _normalize_dependency(dep: str) -> str:
    return dep.split(";", 1)[0].strip()


def _canonical_project_name(value: str) -> str:
    return _PROJECT_NAME_SEPARATOR.sub("-", value).lower()


def _dependency_project_name(dependency: str) -> str:
    match = _DEPENDENCY_NAME.match(dependency.strip())
    if match is None:
        raise SystemExit(f"Unable to resolve dependency project name: {dependency}")
    return _canonical_project_name(match.group())


def _collect_runtime_dependencies() -> list[str]:
    projects = [
        (pyproject, tomllib.loads(pyproject.read_text(encoding="utf-8")))
        for pyproject in sorted(REPO_ROOT.glob("src/**/pyproject.toml"))
    ]
    local_project_names = {
        _canonical_project_name(str(data["project"]["name"])) for _pyproject, data in projects
    }
    deps: dict[str, str] = {}
    for pyproject, data in projects:
        for dep in data.get("project", {}).get("dependencies", []):
            normalized = _normalize_dependency(dep)
            if "==" not in normalized:
                raise SystemExit(
                    f"Floating runtime dependency still present in {pyproject}: {normalized}"
                )
            if _dependency_project_name(normalized) in local_project_names:
                continue
            deps[normalized.lower()] = normalized
    return sorted(deps.values(), key=str.lower)


def _render_runtime_input(deps: list[str]) -> str:
    header = [
        "# Generated by scripts/development/update_shared_runtime_lock.py",
        "# Direct runtime dependency union across lotus-core services and shared libs.",
        "",
    ]
    return "\n".join(header + deps) + "\n"


def _normalize_compiled_lock(content: str, *, platform: str) -> str:
    lines = content.splitlines()
    first_requirement = next(
        (index for index, line in enumerate(lines) if line and not line.startswith(("#", " "))),
        None,
    )
    if first_requirement is None:
        raise SystemExit("pip-tools produced an empty runtime dependency closure")
    body = "\n".join(lines[first_requirement:])
    for source in (
        "/work/shared-runtime.in",
        str(RUNTIME_INPUT.resolve()),
        str(RUNTIME_INPUT.resolve()).replace("\\", "/"),
    ):
        body = body.replace(source, "shared-runtime.in")
    body = body.replace("\\", "/")
    return "\n".join(
        (
            "# Generated by scripts/development/update_shared_runtime_lock.py; do not edit.",
            (
                f"# Generator: pip=={PIP_VERSION}; pip-tools=={PIP_TOOLS_VERSION}; "
                f"Python 3.11; platform {platform}."
            ),
            "# Input: requirements/shared-runtime.in.",
            "",
            body.rstrip(),
            "",
        )
    )


def _compile_linux_runtime_lock(*, upgrade_packages: tuple[str, ...] = ()) -> str:
    invalid = [name for name in upgrade_packages if not re.fullmatch(r"[A-Za-z0-9_.-]+", name)]
    if invalid:
        raise SystemExit(f"Invalid --upgrade-package value: {invalid[0]}")
    temp_dir = Path(tempfile.mkdtemp(prefix="lotus-runtime-lock-"))
    try:
        temp_input = temp_dir / "shared-runtime.in"
        temp_lock = temp_dir / "shared-runtime.lock.txt"
        shutil.copy2(RUNTIME_INPUT, temp_input)
        if RUNTIME_LOCK.exists():
            shutil.copy2(RUNTIME_LOCK, temp_lock)
        upgrade_options = " ".join(f"--upgrade-package {name}" for name in upgrade_packages)
        shell_command = (
            f"python -m pip install -q --disable-pip-version-check pip=={PIP_VERSION} "
            f"pip-tools=={PIP_TOOLS_VERSION} && "
            "python -m piptools compile --quiet --resolver=backtracking --strip-extras "
            f"--allow-unsafe {upgrade_options} --output-file=/work/shared-runtime.lock.txt "
            "/work/shared-runtime.in"
        )
        mount = f"type=bind,source={temp_dir.resolve()},target=/work"
        subprocess.run(
            [
                "docker",
                "run",
                "--rm",
                "--platform",
                "linux/amd64",
                "--env",
                "PIP_ROOT_USER_ACTION=ignore",
                "--mount",
                mount,
                LINUX_COMPILE_IMAGE,
                "sh",
                "-ec",
                shell_command,
            ],
            cwd=REPO_ROOT,
            check=True,
        )
        return _normalize_compiled_lock(
            temp_lock.read_text(encoding="utf-8"), platform="linux/amd64"
        )
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


def _governed_python() -> Path:
    override = os.getenv("LOTUS_LOCK_PYTHON")
    candidates = [Path(override)] if override else []
    if sys.version_info[:2] == (3, 11):
        candidates.append(Path(sys.executable))
    if discovered := shutil.which("python3.11"):
        candidates.append(Path(discovered))
    if sys.platform == "win32" and shutil.which("py"):
        result = subprocess.run(
            ["py", "-3.11", "-c", "import sys; print(sys.executable)"],
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0 and result.stdout.strip():
            candidates.append(Path(result.stdout.strip()))
    for candidate in candidates:
        if not candidate.is_file():
            continue
        result = subprocess.run(
            [str(candidate), "-c", "import sys; print(sys.version_info[:2] == (3, 11))"],
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0 and result.stdout.strip() == "True":
            return candidate.resolve()
    raise SystemExit("Python 3.11 is required; set LOTUS_LOCK_PYTHON to its interpreter path")


def _compile_windows_runtime_lock(*, upgrade_packages: tuple[str, ...] = ()) -> str:
    temp_dir = Path(tempfile.mkdtemp(prefix="lotus-runtime-lock-windows-"))
    try:
        venv_dir = temp_dir / "venv"
        subprocess.run([str(_governed_python()), "-m", "venv", str(venv_dir)], check=True)
        python_bin = venv_dir / "Scripts" / "python.exe"
        subprocess.run(
            [
                str(python_bin),
                "-m",
                "pip",
                "install",
                "--quiet",
                "--disable-pip-version-check",
                f"pip=={PIP_VERSION}",
                f"pip-tools=={PIP_TOOLS_VERSION}",
            ],
            check=True,
        )
        raw_lock = temp_dir / "shared-runtime.lock.txt"
        seed_lock = WINDOWS_RUNTIME_LOCK if WINDOWS_RUNTIME_LOCK.exists() else RUNTIME_LOCK
        shutil.copy2(seed_lock, raw_lock)
        command = [
            str(python_bin),
            "-m",
            "piptools",
            "compile",
            "--quiet",
            "--resolver=backtracking",
            "--strip-extras",
            "--allow-unsafe",
        ]
        for package in upgrade_packages:
            command.extend(("--upgrade-package", package))
        command.extend(("--output-file", str(raw_lock), str(RUNTIME_INPUT)))
        subprocess.run(command, cwd=REPO_ROOT, check=True)
        return _normalize_compiled_lock(
            raw_lock.read_text(encoding="utf-8"), platform="windows/amd64"
        )
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--upgrade-package",
        action="append",
        default=[],
        help="Upgrade only the named package while preserving other compiled pins.",
    )
    parser.add_argument("--check", action="store_true", help="Fail when generated inputs drift.")
    parser.add_argument(
        "--platform",
        choices=("all", "linux", "windows"),
        default="all",
        help="Compile or replay-check one governed platform closure.",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    deps = _collect_runtime_dependencies()
    rendered_input = _render_runtime_input(deps)
    if args.check:
        if RUNTIME_INPUT.read_text(encoding="utf-8") != rendered_input:
            raise SystemExit("shared-runtime.in is not the governed generated input")
    else:
        RUNTIME_INPUT.write_text(rendered_input, encoding="utf-8")
    upgrade_packages = tuple(args.upgrade_package)
    if args.platform in {"all", "linux"}:
        rendered_lock = _compile_linux_runtime_lock(upgrade_packages=upgrade_packages)
        if args.check:
            if RUNTIME_LOCK.read_text(encoding="utf-8") != rendered_lock:
                raise SystemExit("shared-runtime.lock.txt is not the governed compiled closure")
        else:
            RUNTIME_LOCK.write_text(rendered_lock, encoding="utf-8")
    if args.platform in {"all", "windows"} and sys.platform == "win32":
        rendered_windows_lock = _compile_windows_runtime_lock(upgrade_packages=upgrade_packages)
        if args.check:
            if WINDOWS_RUNTIME_LOCK.read_text(encoding="utf-8") != rendered_windows_lock:
                raise SystemExit("shared-runtime-windows.lock.txt is not the governed closure")
        else:
            WINDOWS_RUNTIME_LOCK.write_text(rendered_windows_lock, encoding="utf-8")
    elif args.platform == "windows":
        if sys.platform != "win32":
            raise SystemExit("the Windows runtime closure must be generated on governed Windows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
