"""Compile the deterministic CI/build/test dependency closure with governed provenance."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
TOOLING_INPUT = REPO_ROOT / "requirements" / "ci-tooling.in"
TEST_INPUT = REPO_ROOT / "tests" / "requirements.txt"
LINUX_TOOLING_LOCK = REPO_ROOT / "requirements" / "ci-tooling.lock.txt"
WINDOWS_TOOLING_LOCK = REPO_ROOT / "requirements" / "ci-tooling-windows.lock.txt"
WINDOWS_RUNTIME_LOCK = REPO_ROOT / "requirements" / "shared-runtime-windows.lock.txt"
PIP_TOOLS_VERSION = "7.5.3"
PIP_VERSION = "26.1.2"
GOVERNED_PYTHON = (3, 11)
LINUX_COMPILE_IMAGE = (
    "python:3.11-slim-bookworm@"
    "sha256:97b0eafb29f5ebfba254be840115b2f3bc24ff6ff3de9b905e04b74ee7227ba6"
)
PINNED_REQUIREMENT = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*(?:\[[^]]+\])?==[^\s;]+$")


class ToolingLockError(RuntimeError):
    """Raised when the governed tooling closure cannot be compiled deterministically."""


def _run(command: list[str], *, cwd: Path = REPO_ROOT) -> None:
    subprocess.run(command, cwd=cwd, check=True)


def _input_requirements(path: Path) -> list[str]:
    requirements: list[str] = []
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("#") or line.startswith(("-r ", "-c ")):
            continue
        if not PINNED_REQUIREMENT.fullmatch(line):
            raise ToolingLockError(f"{path}:{line_number} is not an exact dependency pin: {line}")
        requirements.append(line)
    return requirements


def validate_inputs() -> None:
    tooling_text = TOOLING_INPUT.read_text(encoding="utf-8")
    if "-c shared-runtime.lock.txt" not in tooling_text:
        raise ToolingLockError("ci-tooling.in must constrain shared runtime dependency overlap")
    if "-r ../tests/requirements.txt" not in tooling_text:
        raise ToolingLockError("ci-tooling.in must include the governed test dependency inputs")
    for path in (TOOLING_INPUT, TEST_INPUT):
        if not _input_requirements(path):
            raise ToolingLockError(f"{path} contains no governed dependency inputs")


def _governed_python() -> Path:
    override = os.getenv("LOTUS_LOCK_PYTHON")
    candidates: list[Path] = []
    if override:
        candidates.append(Path(override))
    if sys.version_info[:2] == GOVERNED_PYTHON:
        candidates.append(Path(sys.executable))
    discovered = shutil.which("python3.11")
    if discovered:
        candidates.append(Path(discovered))
    if sys.platform == "win32" and shutil.which("py"):
        result = subprocess.run(
            ["py", "-3.11", "-c", "import sys; print(sys.executable)"],
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0 and result.stdout.strip():
            candidates.append(Path(result.stdout.strip()))
    for candidate in candidates:
        if not candidate.is_file():
            continue
        result = subprocess.run(
            [
                str(candidate),
                "-c",
                "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')",
            ],
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0 and result.stdout.strip() == "3.11":
            return candidate.resolve()
    raise ToolingLockError(
        "Python 3.11 is required to compile the lowest-supported-runtime dependency closure; "
        "set LOTUS_LOCK_PYTHON to its interpreter path"
    )


def normalize_compiled_lock(content: str, *, platform: str, root: Path = REPO_ROOT) -> str:
    lines = content.splitlines()
    first_requirement = next(
        (index for index, line in enumerate(lines) if line and not line.startswith(("#", " "))),
        None,
    )
    if first_requirement is None:
        raise ToolingLockError("pip-tools produced an empty dependency closure")
    body = "\n".join(lines[first_requirement:])
    root_variants = {
        str(root.resolve()),
        str(root.resolve()).replace("\\", "/"),
    }
    for root_value in sorted(root_variants, key=len, reverse=True):
        body = body.replace(root_value + "/", "").replace(root_value + "\\", "")
    body = body.replace("\\", "/")
    header = [
        "# Generated by scripts/development/update_ci_tooling_lock.py; do not edit.",
        (
            f"# Generator: pip=={PIP_VERSION}; pip-tools=={PIP_TOOLS_VERSION}; "
            f"Python 3.11; platform {platform}."
        ),
        "# Inputs: requirements/ci-tooling.in and tests/requirements.txt.",
        "",
    ]
    return "\n".join(header) + body.rstrip() + "\n"


def _seed_replay_output(output_path: Path, replay_lock: Path | None) -> None:
    """Seed pip-tools' documented stable-output resolver path for replay checks."""

    if replay_lock is not None:
        if not replay_lock.is_file():
            raise ToolingLockError(f"{replay_lock.name} is unavailable for replay")
        shutil.copyfile(replay_lock, output_path)


def _compile_with_host_python(*, replay_lock: Path | None = None) -> str:
    temp_dir = Path(tempfile.mkdtemp(prefix="lotus-ci-tooling-lock-"))
    try:
        venv_dir = temp_dir / "venv"
        _run([str(_governed_python()), "-m", "venv", str(venv_dir)], cwd=temp_dir)
        python_bin = venv_dir / ("Scripts" if sys.platform == "win32" else "bin") / "python"
        _run(
            [
                str(python_bin),
                "-m",
                "pip",
                "install",
                "--quiet",
                "--disable-pip-version-check",
                f"pip=={PIP_VERSION}",
                f"pip-tools=={PIP_TOOLS_VERSION}",
            ]
        )
        windows_input = temp_dir / "ci-tooling-windows.in"
        windows_input.write_text(
            TOOLING_INPUT.read_text(encoding="utf-8")
            .replace("-c shared-runtime.lock.txt", f"-c {WINDOWS_RUNTIME_LOCK.as_posix()}")
            .replace("-r ../tests/requirements.txt", f"-r {TEST_INPUT.as_posix()}"),
            encoding="utf-8",
        )
        raw_lock = temp_dir / "ci-tooling.raw.txt"
        _seed_replay_output(raw_lock, replay_lock)
        _run(
            [
                str(python_bin),
                "-m",
                "piptools",
                "compile",
                "--quiet",
                "--resolver=backtracking",
                "--strip-extras",
                "--allow-unsafe",
                "--output-file",
                str(raw_lock),
                str(windows_input),
            ]
        )
        return (
            raw_lock.read_text(encoding="utf-8")
            .replace(windows_input.as_posix(), TOOLING_INPUT.as_posix())
            .replace(str(windows_input), str(TOOLING_INPUT))
        )
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


def _compile_linux_in_exact_base(*, replay_lock: Path | None = None) -> str:
    temp_dir = Path(tempfile.mkdtemp(prefix="lotus-ci-tooling-linux-lock-"))
    raw_lock = temp_dir / "ci-tooling.raw.txt"
    _seed_replay_output(raw_lock, replay_lock)
    root_mount = f"type=bind,source={REPO_ROOT.resolve()},target=/repo,readonly"
    output_mount = f"type=bind,source={temp_dir.resolve()},target=/lock-output"
    command = [
        "docker",
        "run",
        "--rm",
        "--platform",
        "linux/amd64",
        "--mount",
        root_mount,
        "--mount",
        output_mount,
        "--workdir",
        "/repo",
        LINUX_COMPILE_IMAGE,
        "sh",
        "-ec",
        (
            f"python -m pip install -q --disable-pip-version-check pip=={PIP_VERSION} "
            f"pip-tools=={PIP_TOOLS_VERSION} && "
            "python -m piptools compile --quiet --resolver=backtracking --strip-extras "
            "--allow-unsafe --output-file=/lock-output/ci-tooling.raw.txt "
            "requirements/ci-tooling.in"
        ),
    ]
    try:
        subprocess.run(command, check=True, capture_output=True, text=True)
        return raw_lock.read_text(encoding="utf-8")
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


def _write_or_check(path: Path, content: str, *, check: bool) -> None:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise ToolingLockError(f"{path.name} is not the governed compiled closure")
        return
    path.write_text(content, encoding="utf-8")


def compile_locks(*, check: bool = False) -> None:
    compile_locks_for_platform(check=check, platform="all")


def compile_locks_for_platform(*, check: bool = False, platform: str) -> None:
    validate_inputs()
    if platform in {"all", "linux"}:
        linux_lock = normalize_compiled_lock(
            _compile_linux_in_exact_base(
                replay_lock=LINUX_TOOLING_LOCK if check else None,
            ),
            platform="linux/amd64",
        )
        _write_or_check(LINUX_TOOLING_LOCK, linux_lock, check=check)
    if platform in {"all", "windows"} and sys.platform == "win32":
        windows_lock = normalize_compiled_lock(
            _compile_with_host_python(
                replay_lock=WINDOWS_TOOLING_LOCK if check else None,
            ),
            platform="windows/amd64",
        )
        _write_or_check(WINDOWS_TOOLING_LOCK, windows_lock, check=check)
    elif platform == "windows":
        raise ToolingLockError("the Windows tooling closure must be generated on governed Windows")
    elif platform not in {"all", "linux"}:
        raise ToolingLockError(f"unsupported lock platform: {platform}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when the committed lock drifts.")
    parser.add_argument(
        "--platform",
        choices=("all", "linux", "windows"),
        default="all",
        help="Compile or replay-check one governed platform closure.",
    )
    args = parser.parse_args()
    compile_locks_for_platform(check=args.check, platform=args.platform)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
