"""Native owned PostgreSQL namespace for canonical FX software-control evidence.

No public cleanup, disabled guard, inherited provider, or shared sequence. The
actual migration and ORM repositories run in an independently marked namespace.
"""

import runpy
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from uuid import uuid4

import pytest
import pytest_asyncio
from alembic.migration import MigrationContext
from alembic.operations import Operations
from portfolio_common.database_models import OutboxEvent, ProcessedEvent
from portfolio_common.database_runtime_profile import DatabasePoolMode
from portfolio_common.db import create_async_database_engine
from portfolio_common.domain.market_data.fx_source import FxSourceScope
from portfolio_common.fx_source_admission import FxSourceAdmission
from portfolio_common.fx_source_models import FxRateSourceCut, FxRateSourceRevision
from sqlalchemy import event, func, select, text
from sqlalchemy.ext.asyncio import async_sessionmaker
from sqlalchemy.orm import Session

from src.services.persistence_service.app.repositories.fx_source_repository import (
    FxSourceRepository,
)
from tests.test_support.fx_source_fixtures import CALENDAR_VERSION, PRINCIPAL


def fx_source_migration(connection):
    path = Path(__file__).resolve().parents[2] / "alembic/versions"
    module = runpy.run_path(str(path / "c179b2c3d540_add_fx_source_revision_cuts.py"))
    assert module["revision"] == "c179b2c3d540"
    assert module["down_revision"] == "c178b2c3d539"
    module["upgrade"].__globals__["op"] = Operations(MigrationContext.configure(connection))
    return module


@pytest.fixture
def fx_source_schema(db_engine):
    from tests import conftest as harness
    from tests.test_support.db_cleanup import (
        authorize_database_cleanup,
        require_database_cleanup_authorization,
    )

    authorization = authorize_database_cleanup(runtime=harness._test_runtime, engine=db_engine)
    require_database_cleanup_authorization(authorization, engine=db_engine)
    schema, marker = "core458_" + uuid4().hex, "core458-owned:" + uuid4().hex
    with db_engine.begin() as connection:
        assert connection.scalar(text("SELECT current_database()")) == authorization.target.database
        assert connection.scalar(text("SELECT session_user")) == authorization.target.username
        connection.execute(text(f'CREATE SCHEMA "{schema}" AUTHORIZATION CURRENT_USER'))
        connection.execute(text(f"""COMMENT ON SCHEMA "{schema}" IS '{marker}'"""))
        for table in ("fx_rates", "processed_events", "outbox_events", "ingestion_jobs"):
            connection.execute(
                text(
                    f'CREATE TABLE "{schema}".{table} '
                    f"(LIKE public.{table} INCLUDING CONSTRAINTS INCLUDING INDEXES)"
                )
            )
            connection.execute(
                text(
                    f'ALTER TABLE "{schema}".{table} ALTER COLUMN id '
                    "ADD GENERATED BY DEFAULT AS IDENTITY"
                )
            )
        for table, column in (
            ("fx_rates", "created_at"),
            ("fx_rates", "updated_at"),
            ("processed_events", "processed_at"),
            ("outbox_events", "created_at"),
            ("ingestion_jobs", "submitted_at"),
        ):
            connection.execute(
                text(f'ALTER TABLE "{schema}".{table} ALTER COLUMN {column} SET DEFAULT now()')
            )
        connection.execute(
            text(
                f'CREATE TABLE "{schema}".ingestion_ops_control '
                "(LIKE public.ingestion_ops_control INCLUDING CONSTRAINTS INCLUDING INDEXES)"
            )
        )
        connection.execute(
            text(
                f'INSERT INTO "{schema}".ingestion_ops_control '
                "(id, mode, updated_by, updated_at) "
                "VALUES (1, 'normal', 'synthetic-fixture', now())"
            )
        )
        connection.execute(text(f'SET LOCAL search_path TO "{schema}", pg_temp'))
        fx_source_migration(connection)["upgrade"]()
    try:
        yield db_engine, schema
    finally:
        require_database_cleanup_authorization(authorization, engine=db_engine)
        with db_engine.begin() as connection:
            identity = connection.execute(
                text("""
                    SELECT current_database(), session_user, pg_get_userbyid(nspowner),
                           obj_description(oid, 'pg_namespace')
                    FROM pg_namespace WHERE nspname=:schema
                """),
                {"schema": schema},
            ).one()
            assert tuple(identity) == (
                authorization.target.database,
                authorization.target.username,
                authorization.target.username,
                marker,
            )
            connection.execute(text(f'DROP SCHEMA "{schema}" CASCADE'))


@dataclass
class FxSourceDatabase:
    sessions: async_sessionmaker
    scope: FxSourceScope
    schema: str

    async def retain(self, cut):
        # Repository controls admit an explicitly synthetic authority fixture;
        # registered HTTP/consumer controls separately prove policy authentication.
        admission = FxSourceAdmission(
            cut, datetime.now(UTC), PRINCIPAL, "SYNTHETIC_ENROLLMENT_V1", CALENDAR_VERSION
        )
        async with self.sessions.begin() as session:
            result = await FxSourceRepository(session).retain_admitted_cut(
                admission, attestation_sha256="a" * 64
            )
        return result

    async def counts(self):
        async with self.sessions() as session:
            return tuple(
                [
                    await session.scalar(select(func.count()).select_from(model))
                    for model in (
                        FxRateSourceCut,
                        FxRateSourceRevision,
                        ProcessedEvent,
                        OutboxEvent,
                    )
                ]
            )


@pytest_asyncio.fixture
async def fx_source_database(fx_source_schema):
    db_engine, schema = fx_source_schema
    engine = create_async_database_engine(
        runtime_identity="lotus-core-test",
        database_url=db_engine.url.render_as_string(hide_password=False),
        pool_mode=DatabasePoolMode.NULL,
    )

    class OwnedFxSession(Session):
        pass

    def bind_namespace(session, transaction, connection):
        connection.execute(text(f'SET LOCAL search_path TO "{schema}", pg_temp'))

    event.listen(OwnedFxSession, "after_begin", bind_namespace)
    sessions = async_sessionmaker(engine, expire_on_commit=False, sync_session_class=OwnedFxSession)
    scope = FxSourceScope("SYNTHETIC_" + uuid4().hex, "SYNTHETIC_PROVIDER", "SYNTHETIC_FEED")
    try:
        async with sessions() as session:
            assert await session.scalar(text("SELECT current_schema()")) == schema
        yield FxSourceDatabase(sessions, scope, schema)
    finally:
        event.remove(OwnedFxSession, "after_begin", bind_namespace)
        await engine.dispose()
