from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

DEFAULT_PROMPT = "go"
DEFAULT_CODEX_BIN = Path(
    r"C:\Users\Sandeep\.vscode\extensions\openai.chatgpt-26.304.20706-win32-x64\bin\windows-x86_64\codex.exe"
)


@dataclass(frozen=True)
class OrchestratorDecision:
    should_trigger: bool
    reason: str


def load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def save_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")


def heartbeat_idle_minutes(heartbeat: dict) -> float:
    return float(heartbeat.get("idle_minutes", 0.0))


def build_runtime_heartbeat_state(heartbeat: dict) -> dict:
    now = datetime.now(UTC)
    last_change_at = heartbeat["last_change_at"]
    idle_minutes = (now - datetime.fromisoformat(last_change_at)).total_seconds() / 60.0
    return {
        **heartbeat,
        "idle_minutes": idle_minutes,
        "evaluated_at": now.isoformat(),
    }


def decide_trigger(
    heartbeat: dict,
    orchestrator_state: dict,
    idle_threshold_minutes: float,
    min_reprompt_minutes: float,
) -> OrchestratorDecision:
    if not heartbeat:
        return OrchestratorDecision(False, "heartbeat-missing")

    if heartbeat_idle_minutes(heartbeat) < idle_threshold_minutes:
        return OrchestratorDecision(False, "below-idle-threshold")

    last_change_at = heartbeat["last_change_at"]
    if orchestrator_state.get("last_trigger_change_at") != last_change_at:
        return OrchestratorDecision(True, "new-idle-window")

    last_trigger_at = orchestrator_state.get("last_trigger_at")
    if not last_trigger_at:
        return OrchestratorDecision(True, "missing-trigger-timestamp")

    elapsed_minutes = (
        datetime.now(UTC) - datetime.fromisoformat(last_trigger_at)
    ).total_seconds() / 60.0
    if elapsed_minutes >= min_reprompt_minutes:
        return OrchestratorDecision(True, "reprompt-window-elapsed")

    return OrchestratorDecision(False, "reprompt-window-active")


def build_codex_command(
    codex_bin: Path,
    repo: Path,
    prompt: str,
    output_file: Path,
) -> list[str]:
    return [
        str(codex_bin),
        "exec",
        "--cd",
        str(repo),
        "--full-auto",
        "--output-last-message",
        str(output_file),
        prompt,
    ]


def trigger_codex(
    codex_bin: Path,
    repo: Path,
    prompt: str,
    output_file: Path,
    dry_run: bool,
) -> tuple[int, list[str]]:
    command = build_codex_command(codex_bin, repo, prompt, output_file)
    if dry_run:
        return 0, command
    completed = subprocess.run(command, cwd=repo, check=False)
    return completed.returncode, command


def update_orchestrator_state(
    previous: dict,
    heartbeat: dict,
    decision: OrchestratorDecision,
    trigger_exit_code: int | None,
    command: list[str] | None,
) -> dict:
    return {
        **previous,
        "last_checked_at": datetime.now(UTC).isoformat(),
        "last_seen_change_at": heartbeat.get("last_change_at"),
        "last_idle_minutes": heartbeat.get("idle_minutes"),
        "last_decision": decision.reason,
        "last_trigger_change_at": (
            heartbeat.get("last_change_at")
            if decision.should_trigger and trigger_exit_code == 0
            else previous.get("last_trigger_change_at")
        ),
        "last_trigger_at": (
            datetime.now(UTC).isoformat()
            if decision.should_trigger and trigger_exit_code == 0
            else previous.get("last_trigger_at")
        ),
        "last_trigger_exit_code": trigger_exit_code,
        "last_command": command,
    }


def print_status(
    heartbeat: dict,
    decision: OrchestratorDecision,
    command: list[str] | None,
) -> None:
    print(
        "[orchestrator] "
        f"branch={heartbeat.get('branch')} "
        f"sha={str(heartbeat.get('head_sha', ''))[:8]} "
        f"idle_minutes={heartbeat.get('idle_minutes', 0.0):.1f} "
        f"decision={decision.reason}"
    )
    if command:
        print("[orchestrator] command=" + subprocess.list2cmdline(command))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Trigger Codex exec when the local heartbeat reports the repo has gone idle."
    )
    parser.add_argument("--repo", type=Path, default=Path.cwd(), help="Repository root.")
    parser.add_argument(
        "--heartbeat-file",
        type=Path,
        default=Path("output/agent-heartbeat.json"),
        help="Heartbeat JSON generated by scripts/agent_heartbeat.py.",
    )
    parser.add_argument(
        "--state-file",
        type=Path,
        default=Path("output/agent-orchestrator.json"),
        help="State file used to rate-limit orchestrator triggers.",
    )
    parser.add_argument(
        "--output-file",
        type=Path,
        default=Path("output/agent-orchestrator-last-message.txt"),
        help="Where the last Codex response should be written.",
    )
    parser.add_argument(
        "--idle-minutes",
        type=float,
        default=5.0,
        help="Minimum idle threshold before the orchestrator will trigger.",
    )
    parser.add_argument(
        "--min-reprompt-minutes",
        type=float,
        default=15.0,
        help="Minimum minutes before triggering again for the same idle window.",
    )
    parser.add_argument(
        "--prompt",
        default=DEFAULT_PROMPT,
        help="Prompt sent to Codex when the orchestrator triggers.",
    )
    parser.add_argument(
        "--codex-bin",
        type=Path,
        default=DEFAULT_CODEX_BIN,
        help="Path to codex.exe.",
    )
    parser.add_argument(
        "--watch",
        action="store_true",
        help="Keep polling until interrupted.",
    )
    parser.add_argument(
        "--poll-seconds",
        type=float,
        default=60.0,
        help="Polling interval for --watch mode.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the command that would run without invoking Codex.",
    )
    return parser.parse_args()


def run_once(
    repo: Path,
    heartbeat_file: Path,
    state_file: Path,
    output_file: Path,
    idle_minutes: float,
    min_reprompt_minutes: float,
    prompt: str,
    codex_bin: Path,
    dry_run: bool,
) -> int:
    heartbeat = load_json(heartbeat_file)
    if not heartbeat:
        print("[orchestrator] heartbeat file missing or empty", file=sys.stderr)
        return 1

    heartbeat = build_runtime_heartbeat_state(heartbeat)
    previous = load_json(state_file)
    decision = decide_trigger(
        heartbeat=heartbeat,
        orchestrator_state=previous,
        idle_threshold_minutes=idle_minutes,
        min_reprompt_minutes=min_reprompt_minutes,
    )

    trigger_exit_code: int | None = None
    command: list[str] | None = None
    if decision.should_trigger:
        trigger_exit_code, command = trigger_codex(
            codex_bin=codex_bin,
            repo=repo,
            prompt=prompt,
            output_file=output_file,
            dry_run=dry_run,
        )

    state = update_orchestrator_state(
        previous=previous,
        heartbeat=heartbeat,
        decision=decision,
        trigger_exit_code=trigger_exit_code,
        command=command,
    )
    save_json(state_file, state)
    print_status(heartbeat, decision, command)
    return 0 if trigger_exit_code in (None, 0) else trigger_exit_code


def run_watch(args: argparse.Namespace) -> int:
    while True:
        exit_code = run_once(
            repo=args.repo.resolve(),
            heartbeat_file=resolve_path(args.repo.resolve(), args.heartbeat_file),
            state_file=resolve_path(args.repo.resolve(), args.state_file),
            output_file=resolve_path(args.repo.resolve(), args.output_file),
            idle_minutes=args.idle_minutes,
            min_reprompt_minutes=args.min_reprompt_minutes,
            prompt=args.prompt,
            codex_bin=args.codex_bin,
            dry_run=args.dry_run,
        )
        if exit_code != 0:
            return exit_code
        time.sleep(args.poll_seconds)


def resolve_path(repo: Path, path: Path) -> Path:
    return path if path.is_absolute() else (repo / path)


def main() -> int:
    args = parse_args()
    repo = args.repo.resolve()
    try:
        if args.watch:
            return run_watch(args)
        return run_once(
            repo=repo,
            heartbeat_file=resolve_path(repo, args.heartbeat_file),
            state_file=resolve_path(repo, args.state_file),
            output_file=resolve_path(repo, args.output_file),
            idle_minutes=args.idle_minutes,
            min_reprompt_minutes=args.min_reprompt_minutes,
            prompt=args.prompt,
            codex_bin=args.codex_bin,
            dry_run=args.dry_run,
        )
    except KeyboardInterrupt:
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
