"""Generate the shared runtime input set and compiled lock file."""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
RUNTIME_INPUT = REPO_ROOT / "requirements" / "shared-runtime.in"
RUNTIME_LOCK = REPO_ROOT / "requirements" / "shared-runtime.lock.txt"
PIP_TOOLS_VERSION = "7.5.3"


def _run(cmd: list[str], *, cwd: Path | None = None) -> None:
    subprocess.run(cmd, cwd=cwd or REPO_ROOT, check=True)


def _normalize_dependency(dep: str) -> str:
    return dep.split(";", 1)[0].strip()


def _collect_runtime_dependencies() -> list[str]:
    deps: dict[str, str] = {}
    for pyproject in sorted(REPO_ROOT.glob("src/**/pyproject.toml")):
        data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
        for dep in data.get("project", {}).get("dependencies", []):
            normalized = _normalize_dependency(dep)
            if "==" not in normalized:
                raise SystemExit(
                    f"Floating runtime dependency still present in {pyproject}: {normalized}"
                )
            deps[normalized.lower()] = normalized
    return sorted(deps.values(), key=str.lower)


def _write_runtime_input(deps: list[str]) -> None:
    header = [
        "# Generated by scripts/update_shared_runtime_lock.py",
        "# Direct runtime dependency union across lotus-core services and shared libs.",
        "",
    ]
    RUNTIME_INPUT.write_text("\n".join(header + deps) + "\n", encoding="utf-8")


def _compile_runtime_lock() -> None:
    temp_dir = Path(tempfile.mkdtemp(prefix="lotus-runtime-lock-"))
    try:
        venv_dir = temp_dir / "venv"
        _run([sys.executable, "-m", "venv", str(venv_dir)], cwd=temp_dir)
        venv_python = venv_dir / ("Scripts" if sys.platform == "win32" else "bin") / "python"
        _run([str(venv_python), "-m", "pip", "install", f"pip-tools=={PIP_TOOLS_VERSION}"])
        _run(
            [
                str(venv_python),
                "-m",
                "piptools",
                "compile",
                "--resolver=backtracking",
                "--strip-extras",
                "--allow-unsafe",
                "--output-file",
                str(RUNTIME_LOCK),
                str(RUNTIME_INPUT),
            ]
        )
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


def main() -> int:
    deps = _collect_runtime_dependencies()
    _write_runtime_input(deps)
    _compile_runtime_lock()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
