from . import reference_data_client_restriction_dto as _client_restriction_dto
from . import reference_data_sustainability_preference_dto as _sustainability_dto

ClientRestrictionProfileIngestionRequest = (
    _client_restriction_dto.ClientRestrictionProfileIngestionRequest
)
ClientRestrictionProfileRecord = _client_restriction_dto.ClientRestrictionProfileRecord
SustainabilityPreferenceProfileIngestionRequest = (
    _sustainability_dto.SustainabilityPreferenceProfileIngestionRequest
)
SustainabilityPreferenceProfileRecord = _sustainability_dto.SustainabilityPreferenceProfileRecord
