from __future__ import annotations

from . import reference_data_benchmark_dto as _benchmark_dto
from . import reference_data_cashflow_planning_dto as _cashflow_planning_dto
from . import reference_data_client_preference_dto as _client_preference_dto
from . import reference_data_instrument_eligibility_dto as _instrument_eligibility_dto
from . import reference_data_mandate_dto as _mandate_dto
from . import reference_data_model_portfolio_dto as _model_portfolio_dto
from . import reference_data_support_dto as _support_dto
from . import reference_data_tax_dto as _tax_dto

ClientRestrictionProfileIngestionRequest = (
    _client_preference_dto.ClientRestrictionProfileIngestionRequest
)
ClientRestrictionProfileRecord = _client_preference_dto.ClientRestrictionProfileRecord
ClientIncomeNeedsScheduleIngestionRequest = (
    _cashflow_planning_dto.ClientIncomeNeedsScheduleIngestionRequest
)
ClientIncomeNeedsScheduleRecord = _cashflow_planning_dto.ClientIncomeNeedsScheduleRecord
SustainabilityPreferenceProfileIngestionRequest = (
    _client_preference_dto.SustainabilityPreferenceProfileIngestionRequest
)
SustainabilityPreferenceProfileRecord = _client_preference_dto.SustainabilityPreferenceProfileRecord
ClientTaxProfileIngestionRequest = _tax_dto.ClientTaxProfileIngestionRequest
ClientTaxProfileRecord = _tax_dto.ClientTaxProfileRecord
ClientTaxRuleSetIngestionRequest = _tax_dto.ClientTaxRuleSetIngestionRequest
ClientTaxRuleSetRecord = _tax_dto.ClientTaxRuleSetRecord
InstrumentEligibilityProfileIngestionRequest = (
    _instrument_eligibility_dto.InstrumentEligibilityProfileIngestionRequest
)
InstrumentEligibilityProfileRecord = _instrument_eligibility_dto.InstrumentEligibilityProfileRecord
ModelPortfolioDefinitionIngestionRequest = (
    _model_portfolio_dto.ModelPortfolioDefinitionIngestionRequest
)
ModelPortfolioDefinitionRecord = _model_portfolio_dto.ModelPortfolioDefinitionRecord
ModelPortfolioTargetIngestionRequest = _model_portfolio_dto.ModelPortfolioTargetIngestionRequest
ModelPortfolioTargetRecord = _model_portfolio_dto.ModelPortfolioTargetRecord
CashAccountMasterIngestionRequest = _support_dto.CashAccountMasterIngestionRequest
CashAccountMasterRecord = _support_dto.CashAccountMasterRecord
ClassificationTaxonomyIngestionRequest = _support_dto.ClassificationTaxonomyIngestionRequest
ClassificationTaxonomyRecord = _support_dto.ClassificationTaxonomyRecord
InstrumentLookthroughComponentIngestionRequest = (
    _support_dto.InstrumentLookthroughComponentIngestionRequest
)
InstrumentLookthroughComponentRecord = _support_dto.InstrumentLookthroughComponentRecord
BenchmarkCompositionIngestionRequest = _benchmark_dto.BenchmarkCompositionIngestionRequest
BenchmarkCompositionRecord = _benchmark_dto.BenchmarkCompositionRecord
BenchmarkDefinitionIngestionRequest = _benchmark_dto.BenchmarkDefinitionIngestionRequest
BenchmarkDefinitionRecord = _benchmark_dto.BenchmarkDefinitionRecord
BenchmarkReturnSeriesIngestionRequest = _benchmark_dto.BenchmarkReturnSeriesIngestionRequest
BenchmarkReturnSeriesRecord = _benchmark_dto.BenchmarkReturnSeriesRecord
DiscretionaryMandateBindingIngestionRequest = (
    _mandate_dto.DiscretionaryMandateBindingIngestionRequest
)
DiscretionaryMandateBindingRecord = _mandate_dto.DiscretionaryMandateBindingRecord
IndexDefinitionIngestionRequest = _benchmark_dto.IndexDefinitionIngestionRequest
IndexDefinitionRecord = _benchmark_dto.IndexDefinitionRecord
IndexPriceSeriesIngestionRequest = _benchmark_dto.IndexPriceSeriesIngestionRequest
IndexPriceSeriesRecord = _benchmark_dto.IndexPriceSeriesRecord
IndexReturnSeriesIngestionRequest = _benchmark_dto.IndexReturnSeriesIngestionRequest
IndexReturnSeriesRecord = _benchmark_dto.IndexReturnSeriesRecord
LiquidityReserveRequirementIngestionRequest = (
    _cashflow_planning_dto.LiquidityReserveRequirementIngestionRequest
)
LiquidityReserveRequirementRecord = _cashflow_planning_dto.LiquidityReserveRequirementRecord
PlannedWithdrawalScheduleIngestionRequest = (
    _cashflow_planning_dto.PlannedWithdrawalScheduleIngestionRequest
)
PlannedWithdrawalScheduleRecord = _cashflow_planning_dto.PlannedWithdrawalScheduleRecord
PortfolioBenchmarkAssignmentIngestionRequest = (
    _mandate_dto.PortfolioBenchmarkAssignmentIngestionRequest
)
PortfolioBenchmarkAssignmentRecord = _mandate_dto.PortfolioBenchmarkAssignmentRecord
RiskFreeSeriesIngestionRequest = _benchmark_dto.RiskFreeSeriesIngestionRequest
RiskFreeSeriesRecord = _benchmark_dto.RiskFreeSeriesRecord
