from . import reference_data_tax_profile_dto as _tax_profile_dto
from . import reference_data_tax_rule_set_dto as _tax_rule_set_dto

ClientTaxProfileIngestionRequest = _tax_profile_dto.ClientTaxProfileIngestionRequest
ClientTaxProfileRecord = _tax_profile_dto.ClientTaxProfileRecord
ClientTaxRuleSetIngestionRequest = _tax_rule_set_dto.ClientTaxRuleSetIngestionRequest
ClientTaxRuleSetRecord = _tax_rule_set_dto.ClientTaxRuleSetRecord
