# services/ingestion_service/app/DTOs/transaction_dto.py
from . import transaction_ingestion_request_dto as _transaction_ingestion_request_dto
from . import transaction_model_dto as _transaction_model_dto

Transaction = _transaction_model_dto.Transaction
TransactionIngestionRequest = _transaction_ingestion_request_dto.TransactionIngestionRequest
