"""Registered reference HTTP handlers on an owned, actually migrated PostgreSQL schema."""

import asyncio
import runpy
from pathlib import Path
from time import time
from uuid import uuid4

import httpx
import pytest
import pytest_asyncio
from alembic.migration import MigrationContext
from alembic.operations import Operations
from portfolio_common.database_models import IngestionOpsControl
from portfolio_common.database_runtime_profile import DatabasePoolMode
from portfolio_common.db import create_async_database_engine, get_async_db_session
from portfolio_common.domain.reference_data.classification_history import (
    ClassificationHistoryConflict,
)
from portfolio_common.enterprise_readiness import (
    _enterprise_auth_context_signature,
    _normalize_headers,
)
from portfolio_common.reference_classification_schema import InstrumentClassificationCutRecord
from sqlalchemy import event, text
from sqlalchemy.exc import DBAPIError, IntegrityError
from sqlalchemy.ext.asyncio import async_sessionmaker
from sqlalchemy.orm import Session

from src.services.ingestion_service.app.infrastructure.workflow_stores import (
    SqlAlchemyIngestionJobStore,
)
from src.services.ingestion_service.app.main import app as write_app
from src.services.ingestion_service.app.services import ingestion_job_service as jobs
from src.services.query_control_plane_service.app.main import app as read_app
from tests.test_support.classification_history import retained_cut, selection, source_cut
from tests.test_support.db_cleanup import (
    authorize_database_cleanup,
    require_database_cleanup_authorization,
)

pytestmark = [pytest.mark.asyncio, pytest.mark.integration_db, pytest.mark.db_direct]
TABLE = "instrument_classification_cuts"
WRITE_PATH = "/ingest/reference/classification-taxonomy"
READ_PATH = "/integration/reference/classification-taxonomy"


def migration(connection):
    root = next(
        parent
        for parent in Path(__file__).resolve().parents
        if (parent / "pyproject.toml").is_file()
    )
    path = root / "alembic/versions"
    module = runpy.run_path(str(path / "c183b2c3d544_instrument_classification_history.py"))
    assert module["revision"] == "c183b2c3d544"
    module["upgrade"].__globals__["op"] = Operations(MigrationContext.configure(connection))
    return module


@pytest.fixture
def classification_schema(db_engine):
    from tests import conftest as harness

    authorization = authorize_database_cleanup(runtime=harness._test_runtime, engine=db_engine)
    schema, marker = "classification_" + uuid4().hex, "owned:" + uuid4().hex
    require_database_cleanup_authorization(authorization, engine=db_engine)
    with db_engine.begin() as connection:
        assert connection.scalar(text("SELECT current_database()")) == authorization.target.database
        assert connection.scalar(text("SELECT session_user")) == authorization.target.username
        connection.execute(text(f'CREATE SCHEMA "{schema}" AUTHORIZATION CURRENT_USER'))
        connection.execute(text(f"""COMMENT ON SCHEMA "{schema}" IS '{marker}'"""))
        for table in ("ingestion_jobs", "ingestion_job_failures", "ingestion_ops_control"):
            connection.execute(
                text(f'CREATE TABLE "{schema}".{table} (LIKE public.{table} INCLUDING CONSTRAINTS)')
            )
        connection.execute(
            text(
                f'ALTER TABLE "{schema}".ingestion_jobs ALTER COLUMN id '
                "ADD GENERATED BY DEFAULT AS IDENTITY"
            )
        )
        connection.execute(
            text(
                f'ALTER TABLE "{schema}".ingestion_job_failures ALTER COLUMN id '
                "ADD GENERATED BY DEFAULT AS IDENTITY"
            )
        )
        for table, columns in (
            ("ingestion_jobs", "tenant_id, job_id"),
            ("ingestion_jobs", "job_id"),
            ("ingestion_ops_control", "id"),
        ):
            connection.execute(text(f'ALTER TABLE "{schema}".{table} ADD UNIQUE ({columns})'))
        for table, column in (
            ("ingestion_jobs", "submitted_at"),
            ("ingestion_job_failures", "failed_at"),
            ("ingestion_ops_control", "updated_at"),
        ):
            connection.execute(
                text(f'ALTER TABLE "{schema}".{table} ALTER COLUMN {column} SET DEFAULT now()')
            )
        connection.execute(text(f'SET LOCAL search_path TO "{schema}", pg_temp'))
        migration(connection)["upgrade"]()
    try:
        yield db_engine, schema
    finally:
        require_database_cleanup_authorization(authorization, engine=db_engine)
        with db_engine.begin() as connection:
            identity = connection.execute(
                text(
                    "SELECT current_database(), session_user, pg_get_userbyid(nspowner), "
                    "obj_description(oid, 'pg_namespace') FROM pg_namespace WHERE nspname=:schema"
                ),
                {"schema": schema},
            ).one()
            assert tuple(identity) == (
                authorization.target.database,
                authorization.target.username,
                authorization.target.username,
                marker,
            )
            connection.execute(text(f'DROP SCHEMA "{schema}" CASCADE'))


@pytest_asyncio.fixture
async def classification_sessions(classification_schema, monkeypatch):
    db_engine, schema = classification_schema
    engine = create_async_database_engine(
        runtime_identity="lotus-core-test",
        database_url=db_engine.url.render_as_string(hide_password=False),
        pool_mode=DatabasePoolMode.NULL,
    )

    class OwnedClassificationSession(Session):
        pass

    def bind_namespace(session, transaction, connection):
        connection.execute(text(f'SET LOCAL search_path TO "{schema}", pg_temp'))

    event.listen(OwnedClassificationSession, "after_begin", bind_namespace)
    factory = async_sessionmaker(
        engine, expire_on_commit=False, sync_session_class=OwnedClassificationSession
    )

    async def sessions():
        async with factory() as session:
            yield session

    monkeypatch.setenv("ENTERPRISE_ENFORCE_AUTHZ", "true")
    monkeypatch.setenv("ENTERPRISE_PRIMARY_KEY_ID", "synthetic-key")
    monkeypatch.setenv("ENTERPRISE_AUTH_CONTEXT_HMAC_SECRET", "synthetic-context-secret")
    monkeypatch.setattr(jobs, "get_async_db_session", sessions)
    monkeypatch.setitem(write_app.dependency_overrides, get_async_db_session, sessions)
    monkeypatch.setitem(read_app.dependency_overrides, get_async_db_session, sessions)

    def job_service():
        return jobs.IngestionJobService(
            job_store=SqlAlchemyIngestionJobStore(
                session_factory=sessions,
                fingerprint_key_id="synthetic-key",
                fingerprint_hmac_secret="synthetic-secret",
                fingerprint_previous_keys={},
            )
        )

    monkeypatch.setitem(write_app.dependency_overrides, jobs.get_ingestion_job_service, job_service)
    async with factory.begin() as session:
        session.add(IngestionOpsControl(id=1, mode="normal", updated_by="synthetic-proof"))
    try:
        yield factory
    finally:
        await engine.dispose()
        event.remove(OwnedClassificationSession, "after_begin", bind_namespace)


def headers(*, write=False):
    result = {
        "X-Actor-Id": "synthetic-operator",
        "X-Tenant-Id": "synthetic-reference",
        "X-Role": "ops",
        "X-Correlation-Id": "synthetic-correlation",
        "X-Service-Identity": "synthetic-source",
        "X-Capabilities": (
            "ingestion.reference_data.write"
            if write
            else "source_data.instrument_reference_bundle.read"
        ),
        "X-Enterprise-Auth-Key-Id": "synthetic-key",
        "X-Enterprise-Auth-Timestamp": str(int(time())),
    }
    result["X-Enterprise-Auth-Signature"] = _enterprise_auth_context_signature(
        _normalize_headers(result), "synthetic-context-secret"
    )
    if write:
        result["X-Idempotency-Key"] = uuid4().hex
    return result


async def read_history(client, cut, **changes):
    selected = selection(cut, **changes)
    response = await client.post(
        READ_PATH,
        headers=headers(),
        json={
            "as_of_date": selected.period_end.isoformat(),
            "history_selection": selected.model_dump(mode="json"),
        },
    )
    assert response.status_code == 200, response.text
    return response.json()


async def test_registered_handlers_preserve_original_correction_and_refusals(
    classification_sessions,
):
    original = source_cut()
    cut_a = retained_cut(original)
    rows = [row.model_dump(mode="json") for row in original.assignments]
    rows[0]["effective_to"] = "2026-01-16"
    rows.append(
        rows[0]
        | {
            "effective_from": "2026-01-16",
            "effective_to": "2026-02-01",
            "group_id": "FINANCE",
            "source_record_id": "SYNTHETIC_RECLASS",
        }
    )
    corrected = source_cut(source_version=2, predecessor_cut_id=cut_a.cut_id, assignments=rows)
    cut_b = retained_cut(corrected)
    async with (
        httpx.AsyncClient(
            transport=httpx.ASGITransport(app=write_app), base_url="http://test"
        ) as writer,
        httpx.AsyncClient(
            transport=httpx.ASGITransport(app=read_app), base_url="http://test"
        ) as reader,
    ):
        for source in (original, corrected):
            response = await writer.post(
                WRITE_PATH,
                headers=headers(write=True),
                json={
                    "assignment_cut": source.model_dump(mode="json"),
                },
            )
            assert response.status_code == 202, response.text
        first = await read_history(reader, cut_a)
        second = await read_history(reader, cut_b)
        assert first["history"]["status"] == second["history"]["status"] == "COMPLETE"
        assert first["history"]["assignments"] == original.model_dump(mode="json")["assignments"]
        assert len(second["history"]["assignments"]) == 3
        assert first["source_evidence_current"] is False
        assert first["history"]["compatibility"] == "UNAVAILABLE"
        assert first["records"] == []
        replay = await read_history(reader, cut_a)
        assert replay["history"] == first["history"]
        assert replay["content_hash"] == first["content_hash"]
        for changes in (
            {"producer_id": "FOREIGN"},
            {"classification_set_id": "FOREIGN"},
            {"source_version": 99},
            {"cut_id": "sha256:" + "0" * 64},
            {"content_hash": "sha256:" + "0" * 64},
            {"known_at": "2026-02-01T00:00:00Z"},
            {"source_as_of": "2026-01-31T00:00:00Z"},
            {"expected_security_ids": ["SYNTHETIC_A"]},
        ):
            refused = await read_history(reader, cut_a, **changes)
            assert refused["history"]["status"] == "UNAVAILABLE"
            assert refused["history"]["assignments"] == []
        conflict = source_cut(assignments=[rows[1]])
        response = await writer.post(
            WRITE_PATH,
            headers=headers(write=True),
            json={
                "assignment_cut": conflict.model_dump(mode="json"),
            },
        )
        assert response.status_code == 409, response.text
        partial = source_cut(source_record_id="SYNTHETIC_PARTIAL", assignments=[rows[1]])
        response = await writer.post(
            WRITE_PATH,
            headers=headers(write=True),
            json={
                "assignment_cut": partial.model_dump(mode="json"),
            },
        )
        assert response.status_code == 202, response.text
        missing = await read_history(reader, retained_cut(partial))
        assert missing["history"]["status"] == "PARTIAL"
        assert missing["history"]["missing_security_ids"] == ["SYNTHETIC_A"]


async def test_append_race_replay_and_immutable_database_guards(classification_sessions):
    from src.services.ingestion_service.app.services.classification_history_writer import (
        ClassificationHistoryWriter,
    )

    async def append(source):
        async with classification_sessions.begin() as session:
            return await ClassificationHistoryWriter(session).append(source)

    results = await asyncio.gather(append(source_cut()), append(source_cut()))
    assert results[0] == results[1]
    original = results[0]
    corrected_rows = [row.model_dump(mode="json") for row in original.source.assignments]
    corrected_rows[0]["group_id"] = "FINANCE"
    corrections = (
        source_cut(source_version=2, predecessor_cut_id=original.cut_id),
        source_cut(
            source_version=2, predecessor_cut_id=original.cut_id, assignments=corrected_rows
        ),
    )
    competing = await asyncio.gather(
        *(append(source) for source in corrections), return_exceptions=True
    )
    assert sum(isinstance(result, ClassificationHistoryConflict) for result in competing) == 1
    assert await append(source_cut()) == original
    for changes in (
        {"source_version": 3, "predecessor_cut_id": original.cut_id},
        {"source_version": 2, "predecessor_cut_id": original.cut_id, "producer_id": "FOREIGN"},
        {"generated_at": "2099-01-01T00:00:00Z", "source_record_id": "SYNTHETIC_FUTURE"},
    ):
        with pytest.raises(ClassificationHistoryConflict):
            await append(source_cut(**changes))
    for statement in (
        f"UPDATE {TABLE} SET received_at=now()",
        f"DELETE FROM {TABLE}",
        f"TRUNCATE {TABLE}",
    ):
        async with classification_sessions() as session:
            with pytest.raises(DBAPIError, match="CLASSIFICATION_CUT_IMMUTABLE"):
                await session.execute(text(statement))
            await session.rollback()
    async with classification_sessions() as session:
        assert await session.scalar(text(f"SELECT count(*) FROM {TABLE}")) == 2


async def test_malformed_retained_content_is_unavailable(classification_sessions):
    cut = retained_cut()
    async with classification_sessions.begin() as session:
        await session.execute(
            text(f"""INSERT INTO {TABLE}
            (cut_id, content_hash, producer_id, classification_set_id, source_record_id,
             source_version, payload, received_at)
            VALUES (:cut, :hash, :producer, :classification, :record, 1, '{{}}', now())"""),
            {
                "cut": cut.cut_id,
                "hash": cut.content_hash,
                "producer": cut.source.producer_id,
                "classification": cut.source.classification_set_id,
                "record": cut.source.source_record_id,
            },
        )
    async with httpx.AsyncClient(
        transport=httpx.ASGITransport(app=read_app), base_url="http://test"
    ) as reader:
        result = await read_history(reader, cut)
        assert result["history"]["status"] == "UNAVAILABLE"
        assert result["history"]["retained_cut"] is None
        assert not result["history"]["assignments"]


async def test_actual_migration_empty_downgrade_and_nonempty_refusal(classification_schema):
    engine, schema = classification_schema
    with engine.begin() as connection:
        connection.execute(text(f'SET LOCAL search_path TO "{schema}", pg_temp'))
        connection.execute(text(f"TRUNCATE {TABLE}"))
        migration(connection)["downgrade"]()
        migration(connection)["upgrade"]()
        cut = retained_cut()
        connection.execute(
            text(f"""INSERT INTO {TABLE}
            (cut_id, content_hash, producer_id, classification_set_id, source_record_id,
             source_version, payload, received_at)
            VALUES (:cut, :hash, 'synthetic', 'sector', 'jan', 1, '{{}}', now())"""),
            {"cut": cut.cut_id, "hash": cut.content_hash},
        )
    with engine.begin() as connection:
        connection.execute(text(f'SET LOCAL search_path TO "{schema}", pg_temp'))
        with pytest.raises(DBAPIError, match="CLASSIFICATION_CUT_DOWNGRADE_NONEMPTY"):
            migration(connection)["downgrade"]()


async def test_repeatable_snapshot_cannot_authorize_empty_teardown(classification_schema):
    engine, schema = classification_schema
    with engine.connect().execution_options(isolation_level="REPEATABLE READ") as connection:
        with connection.begin():
            connection.execute(text(f'SET LOCAL search_path TO "{schema}", pg_temp'))
            assert connection.scalar(text(f"SELECT count(*) FROM {TABLE}")) == 0
            with pytest.raises(RuntimeError, match="CLASSIFICATION_CUT_DOWNGRADE_ISOLATION"):
                migration(connection)["downgrade"]()
            with pytest.raises(DBAPIError, match="CLASSIFICATION_CUT_TRUNCATE_ISOLATION"):
                connection.execute(text(f"TRUNCATE {TABLE}"))


async def test_waiting_truncate_observes_newly_committed_custody(classification_sessions):
    from src.services.ingestion_service.app.services.classification_history_writer import (
        ClassificationHistoryWriter,
    )

    async with classification_sessions() as writer, classification_sessions() as truncator:
        await ClassificationHistoryWriter(writer).append(source_cut())
        pid = await truncator.scalar(text("SELECT pg_backend_pid()"))
        task = asyncio.create_task(truncator.execute(text(f"TRUNCATE {TABLE}")))

        async def observed_lock_wait():
            while True:
                async with classification_sessions() as observer:
                    if await observer.scalar(
                        text("SELECT wait_event_type='Lock' FROM pg_stat_activity WHERE pid=:pid"),
                        {"pid": pid},
                    ):
                        return
                await asyncio.sleep(0.01)

        try:
            await asyncio.wait_for(observed_lock_wait(), timeout=5)
            await writer.commit()
            with pytest.raises(DBAPIError, match="CLASSIFICATION_CUT_IMMUTABLE"):
                await asyncio.wait_for(task, timeout=5)
        finally:
            if not task.done():
                task.cancel()
                await asyncio.gather(task, return_exceptions=True)
            await writer.rollback()
            await truncator.rollback()
    async with classification_sessions() as session:
        assert await session.scalar(text(f"SELECT count(*) FROM {TABLE}")) == 1


async def test_database_refuses_foreign_predecessor_duplicate_revision_and_fork(
    classification_sessions,
):
    from src.services.ingestion_service.app.services.classification_history_writer import (
        ClassificationHistoryWriter,
    )

    async with classification_sessions.begin() as session:
        writer = ClassificationHistoryWriter(session)
        original = await writer.append(source_cut())
        corrected = await writer.append(
            source_cut(source_version=2, predecessor_cut_id=original.cut_id)
        )
    rows = [row.model_dump(mode="json") for row in original.source.assignments]
    rows[0]["group_id"] = "FINANCE"
    attempts = (
        (
            source_cut(
                producer_id="FOREIGN", source_version=2, predecessor_cut_id=corrected.cut_id
            ),
            "23503",
        ),
        (source_cut(source_version=3, predecessor_cut_id=original.cut_id), "23505"),
        (source_cut(assignments=rows), "23505"),
    )
    for source, sqlstate in attempts:
        retained = retained_cut(source, received_at=original.received_at)
        async with classification_sessions() as session:
            session.add(
                InstrumentClassificationCutRecord(
                    cut_id=retained.cut_id,
                    content_hash=retained.content_hash,
                    producer_id=source.producer_id,
                    classification_set_id=source.classification_set_id,
                    source_record_id=source.source_record_id,
                    source_version=source.source_version,
                    predecessor_cut_id=source.predecessor_cut_id,
                    payload=source.model_dump(mode="json"),
                    received_at=retained.received_at,
                )
            )
            with pytest.raises(IntegrityError) as error:
                await session.flush()
            assert error.value.orig.sqlstate == sqlstate
            await session.rollback()
    async with classification_sessions() as session:
        assert await session.scalar(text(f"SELECT count(*) FROM {TABLE}")) == 2
