from enum import StrEnum


class DividendValidationReasonCode(StrEnum):
    INVALID_TRANSACTION_TYPE = "DIVIDEND_001_INVALID_TRANSACTION_TYPE"
    MISSING_SETTLEMENT_DATE = "DIVIDEND_002_MISSING_SETTLEMENT_DATE"
    NON_ZERO_QUANTITY = "DIVIDEND_003_NON_ZERO_QUANTITY"
    NON_ZERO_PRICE = "DIVIDEND_004_NON_ZERO_PRICE"
    NON_POSITIVE_GROSS_AMOUNT = "DIVIDEND_005_NON_POSITIVE_GROSS_AMOUNT"
    MISSING_TRADE_CURRENCY = "DIVIDEND_006_MISSING_TRADE_CURRENCY"
    MISSING_BOOK_CURRENCY = "DIVIDEND_007_MISSING_BOOK_CURRENCY"
    INVALID_DATE_ORDER = "DIVIDEND_008_INVALID_DATE_ORDER"
    MISSING_LINKAGE_IDENTIFIER = "DIVIDEND_009_MISSING_LINKAGE_IDENTIFIER"
    MISSING_POLICY_METADATA = "DIVIDEND_010_MISSING_POLICY_METADATA"
    MISSING_EXTERNAL_CASH_LINK = "DIVIDEND_011_MISSING_EXTERNAL_CASH_LINK"
