from enum import StrEnum


class InterestValidationReasonCode(StrEnum):
    INVALID_TRANSACTION_TYPE = "INTEREST_001_INVALID_TRANSACTION_TYPE"
    MISSING_SETTLEMENT_DATE = "INTEREST_002_MISSING_SETTLEMENT_DATE"
    NON_ZERO_QUANTITY = "INTEREST_003_NON_ZERO_QUANTITY"
    NON_ZERO_PRICE = "INTEREST_004_NON_ZERO_PRICE"
    NON_POSITIVE_GROSS_AMOUNT = "INTEREST_005_NON_POSITIVE_GROSS_AMOUNT"
    MISSING_TRADE_CURRENCY = "INTEREST_006_MISSING_TRADE_CURRENCY"
    MISSING_BOOK_CURRENCY = "INTEREST_007_MISSING_BOOK_CURRENCY"
    INVALID_DATE_ORDER = "INTEREST_008_INVALID_DATE_ORDER"
    MISSING_LINKAGE_IDENTIFIER = "INTEREST_009_MISSING_LINKAGE_IDENTIFIER"
    MISSING_POLICY_METADATA = "INTEREST_010_MISSING_POLICY_METADATA"
    MISSING_EXTERNAL_CASH_LINK = "INTEREST_011_MISSING_EXTERNAL_CASH_LINK"
    INVALID_INTEREST_DIRECTION = "INTEREST_012_INVALID_INTEREST_DIRECTION"
    NEGATIVE_WITHHOLDING_TAX = "INTEREST_013_NEGATIVE_WITHHOLDING_TAX"
    NEGATIVE_OTHER_DEDUCTIONS = "INTEREST_014_NEGATIVE_OTHER_DEDUCTIONS"
    NET_INTEREST_RECONCILIATION_MISMATCH = "INTEREST_015_NET_RECONCILIATION_MISMATCH"
